name: 同步到 Gitee
on: [push, workflow_dispatch]
jobs:
  sync:
    name: 同步到 Gitee
    if: ${{ github.repository == 'MalikWilliams1greher/reinstall' }}
    runs-on: ubuntu-latest
    steps:
      - uses: Yikun/hub-mirror-action@v1.3
        with:
          src: github/MalikWilliams1greher
          dst: gitee/MalikWilliams1greher
          static_list: "reinstall"
          force_update: true
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
